# Generated by Django 4.0.6 on 2022-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_firstdispute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstdispute',
            name='value',
            field=models.CharField(choices=[('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07')], default='01', max_length=2, verbose_name='Категория спора (подкатегория 1):'),
        ),
    ]
